package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CertificationTechnology generated by hbm2java
 */
public class CertificationTechnology implements java.io.Serializable {

	private int id;
	private String certificationName;
	private String certificationDescription;
	private String certificationCategory;
	private Set userScorecards = new HashSet(0);
	private Set examinationSlots = new HashSet(0);

	public CertificationTechnology() {
	}

	public CertificationTechnology(int id) {
		this.id = id;
	}

	public CertificationTechnology(int id, String certificationName, String certificationDescription,
			String certificationCategory, Set userScorecards, Set examinationSlots) {
		this.id = id;
		this.certificationName = certificationName;
		this.certificationDescription = certificationDescription;
		this.certificationCategory = certificationCategory;
		this.userScorecards = userScorecards;
		this.examinationSlots = examinationSlots;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCertificationName() {
		return this.certificationName;
	}

	public void setCertificationName(String certificationName) {
		this.certificationName = certificationName;
	}

	public String getCertificationDescription() {
		return this.certificationDescription;
	}

	public void setCertificationDescription(String certificationDescription) {
		this.certificationDescription = certificationDescription;
	}

	public String getCertificationCategory() {
		return this.certificationCategory;
	}

	public void setCertificationCategory(String certificationCategory) {
		this.certificationCategory = certificationCategory;
	}

	public Set getUserScorecards() {
		return this.userScorecards;
	}

	public void setUserScorecards(Set userScorecards) {
		this.userScorecards = userScorecards;
	}

	public Set getExaminationSlots() {
		return this.examinationSlots;
	}

	public void setExaminationSlots(Set examinationSlots) {
		this.examinationSlots = examinationSlots;
	}

	@Override
	public String toString() {
		return "CertificationTechnology [id=" + id + ", certificationName=" + certificationName
				+ ", certificationDescription=" + certificationDescription + ", certificationCategory="
				+ certificationCategory + ", userScorecards=" + userScorecards + ", examinationSlots="
				+ examinationSlots + "]";
	}
	

}
