package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.Arrays;

/**
 * EmailTemplate generated by hbm2java
 */
public class EmailTemplate implements java.io.Serializable {

	private int id;
	private String templateSlug;
	private byte[] templateContent;

	public EmailTemplate() {
	}

	public EmailTemplate(int id) {
		this.id = id;
	}

	public EmailTemplate(int id, String templateSlug, byte[] templateContent) {
		this.id = id;
		this.templateSlug = templateSlug;
		this.templateContent = templateContent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTemplateSlug() {
		return this.templateSlug;
	}

	public void setTemplateSlug(String templateSlug) {
		this.templateSlug = templateSlug;
	}

	public byte[] getTemplateContent() {
		return this.templateContent;
	}

	public void setTemplateContent(byte[] templateContent) {
		this.templateContent = templateContent;
	}

	@Override
	public String toString() {
		return "EmailTemplate [id=" + id + ", templateSlug=" + templateSlug + ", templateContent="
				+ Arrays.toString(templateContent) + "]";
	}
	

}
