package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

/**
 * ExamQuestionMultipleAnswers generated by hbm2java
 */
public class ExamQuestionMultipleAnswers implements java.io.Serializable {

	private int id;
	private ExamQuestions examQuestions;
	private String examinationAnswers;

	public ExamQuestionMultipleAnswers() {
	}

	public ExamQuestionMultipleAnswers(int id) {
		this.id = id;
	}

	public ExamQuestionMultipleAnswers(int id, ExamQuestions examQuestions, String examinationAnswers) {
		this.id = id;
		this.examQuestions = examQuestions;
		this.examinationAnswers = examinationAnswers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ExamQuestions getExamQuestions() {
		return this.examQuestions;
	}

	public void setExamQuestions(ExamQuestions examQuestions) {
		this.examQuestions = examQuestions;
	}

	public String getExaminationAnswers() {
		return this.examinationAnswers;
	}

	public void setExaminationAnswers(String examinationAnswers) {
		this.examinationAnswers = examinationAnswers;
	}

	@Override
	public String toString() {
		return "ExamQuestionMultipleAnswers [id=" + id + ", examQuestions=" + examQuestions + ", examinationAnswers="
				+ examinationAnswers + "]";
	}

	
}
