package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ExamQuestions generated by hbm2java
 */
public class ExamQuestions implements java.io.Serializable {

	private int id;
	private String certificationType;
	private String certificationQuestion;
	private Integer certificationAnswerId;
	private Set examQuestionMultipleAnswerses = new HashSet(0);

	public ExamQuestions() {
	}

	public ExamQuestions(int id) {
		this.id = id;
	}

	public ExamQuestions(int id, String certificationType, String certificationQuestion, Integer certificationAnswerId,
			Set examQuestionMultipleAnswerses) {
		this.id = id;
		this.certificationType = certificationType;
		this.certificationQuestion = certificationQuestion;
		this.certificationAnswerId = certificationAnswerId;
		this.examQuestionMultipleAnswerses = examQuestionMultipleAnswerses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCertificationType() {
		return this.certificationType;
	}

	public void setCertificationType(String certificationType) {
		this.certificationType = certificationType;
	}

	public String getCertificationQuestion() {
		return this.certificationQuestion;
	}

	public void setCertificationQuestion(String certificationQuestion) {
		this.certificationQuestion = certificationQuestion;
	}

	public Integer getCertificationAnswerId() {
		return this.certificationAnswerId;
	}

	public void setCertificationAnswerId(Integer certificationAnswerId) {
		this.certificationAnswerId = certificationAnswerId;
	}

	public Set getExamQuestionMultipleAnswerses() {
		return this.examQuestionMultipleAnswerses;
	}

	public void setExamQuestionMultipleAnswerses(Set examQuestionMultipleAnswerses) {
		this.examQuestionMultipleAnswerses = examQuestionMultipleAnswerses;
	}

	@Override
	public String toString() {
		return "ExamQuestions [id=" + id + ", certificationType=" + certificationType + ", certificationQuestion="
				+ certificationQuestion + ", certificationAnswerId=" + certificationAnswerId
				+ ", examQuestionMultipleAnswerses=" + examQuestionMultipleAnswerses + "]";
	}
	

}
