package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

/**
 * PaymentDetails generated by hbm2java
 */
public class PaymentDetails implements java.io.Serializable {

	private int id;
	private ExaminationSlot examinationSlot;
	private User user;
	private Float paymentAmount;
	private String currency;

	public PaymentDetails() {
	}

	public PaymentDetails(int id) {
		this.id = id;
	}

	public PaymentDetails(int id, ExaminationSlot examinationSlot, User user, Float paymentAmount, String currency) {
		this.id = id;
		this.examinationSlot = examinationSlot;
		this.user = user;
		this.paymentAmount = paymentAmount;
		this.currency = currency;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ExaminationSlot getExaminationSlot() {
		return this.examinationSlot;
	}

	public void setExaminationSlot(ExaminationSlot examinationSlot) {
		this.examinationSlot = examinationSlot;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Float getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Float paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Override
	public String toString() {
		return "PaymentDetails [id=" + id + ", examinationSlot=" + examinationSlot + ", user=" + user
				+ ", paymentAmount=" + paymentAmount + ", currency=" + currency + "]";
	}
	

}
