package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int id;
	private User user;
	private String firstName;
	private String lastName;
	private String gender;

	public Profile() {
	}

	public Profile(int id) {
		this.id = id;
	}

	public Profile(int id, User user, String firstName, String lastName, String gender) {
		this.id = id;
		this.user = user;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Override
	public String toString() {
		return "Profile [id=" + id + ", user=" + user + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", gender=" + gender + "]";
	}
	

}
