package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.Arrays;

/**
 * SocialAuth generated by hbm2java
 */
public class SocialAuth implements java.io.Serializable {

	private int id;
	private User user;
	private String providerName;
	private byte[] providerResponse;
	private Integer providerId;

	public SocialAuth() {
	}

	public SocialAuth(int id) {
		this.id = id;
	}

	public SocialAuth(int id, User user, String providerName, byte[] providerResponse, Integer providerId) {
		this.id = id;
		this.user = user;
		this.providerName = providerName;
		this.providerResponse = providerResponse;
		this.providerId = providerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	public byte[] getProviderResponse() {
		return this.providerResponse;
	}

	public void setProviderResponse(byte[] providerResponse) {
		this.providerResponse = providerResponse;
	}

	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	@Override
	public String toString() {
		return "SocialAuth [id=" + id + ", user=" + user + ", providerName=" + providerName + ", providerResponse="
				+ Arrays.toString(providerResponse) + ", providerId=" + providerId + "]";
	}
	

}
