package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private UserRole userRole;
	private short status;
	private String email;
	private String username;
	private String password;
	private String authKey;
	private String accessToken;
	private String loggedInIp;
	private Date loggedInAt;
	private String createdIp;
	private Date createdAt;
	private Date updatedAt;
	private Date bannedAt;
	private String bannedReason;
	private Set paymentDetailses = new HashSet(0);
	private Set userScorecards = new HashSet(0);
	private Set examinationSlots = new HashSet(0);
	private Set socialAuths = new HashSet(0);
	private Set profiles = new HashSet(0);

	public User() {
	}

	public User(int id, UserRole userRole, short status) {
		this.id = id;
		this.userRole = userRole;
		this.status = status;
	}

	public User(int id, UserRole userRole, short status, String email, String username, String password, String authKey,
			String accessToken, String loggedInIp, Date loggedInAt, String createdIp, Date createdAt, Date updatedAt,
			Date bannedAt, String bannedReason, Set paymentDetailses, Set userScorecards, Set examinationSlots,
			Set socialAuths, Set profiles) {
		this.id = id;
		this.userRole = userRole;
		this.status = status;
		this.email = email;
		this.username = username;
		this.password = password;
		this.authKey = authKey;
		this.accessToken = accessToken;
		this.loggedInIp = loggedInIp;
		this.loggedInAt = loggedInAt;
		this.createdIp = createdIp;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.bannedAt = bannedAt;
		this.bannedReason = bannedReason;
		this.paymentDetailses = paymentDetailses;
		this.userScorecards = userScorecards;
		this.examinationSlots = examinationSlots;
		this.socialAuths = socialAuths;
		this.profiles = profiles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAuthKey() {
		return this.authKey;
	}

	public void setAuthKey(String authKey) {
		this.authKey = authKey;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getLoggedInIp() {
		return this.loggedInIp;
	}

	public void setLoggedInIp(String loggedInIp) {
		this.loggedInIp = loggedInIp;
	}

	public Date getLoggedInAt() {
		return this.loggedInAt;
	}

	public void setLoggedInAt(Date loggedInAt) {
		this.loggedInAt = loggedInAt;
	}

	public String getCreatedIp() {
		return this.createdIp;
	}

	public void setCreatedIp(String createdIp) {
		this.createdIp = createdIp;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getBannedAt() {
		return this.bannedAt;
	}

	public void setBannedAt(Date bannedAt) {
		this.bannedAt = bannedAt;
	}

	public String getBannedReason() {
		return this.bannedReason;
	}

	public void setBannedReason(String bannedReason) {
		this.bannedReason = bannedReason;
	}

	public Set getPaymentDetailses() {
		return this.paymentDetailses;
	}

	public void setPaymentDetailses(Set paymentDetailses) {
		this.paymentDetailses = paymentDetailses;
	}

	public Set getUserScorecards() {
		return this.userScorecards;
	}

	public void setUserScorecards(Set userScorecards) {
		this.userScorecards = userScorecards;
	}

	public Set getExaminationSlots() {
		return this.examinationSlots;
	}

	public void setExaminationSlots(Set examinationSlots) {
		this.examinationSlots = examinationSlots;
	}

	public Set getSocialAuths() {
		return this.socialAuths;
	}

	public void setSocialAuths(Set socialAuths) {
		this.socialAuths = socialAuths;
	}

	public Set getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set profiles) {
		this.profiles = profiles;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", userRole=" + userRole + ", status=" + status + ", email=" + email + ", username="
				+ username + ", password=" + password + ", authKey=" + authKey + ", accessToken=" + accessToken
				+ ", loggedInIp=" + loggedInIp + ", loggedInAt=" + loggedInAt + ", createdIp=" + createdIp
				+ ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + ", bannedAt=" + bannedAt + ", bannedReason="
				+ bannedReason + ", paymentDetailses=" + paymentDetailses + ", userScorecards=" + userScorecards
				+ ", examinationSlots=" + examinationSlots + ", socialAuths=" + socialAuths + ", profiles=" + profiles
				+ "]";
	}

	
}
