package com.reverse;
// Generated Jan 10, 2018 10:42:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private int id;
	private String roleName;
	private Set users = new HashSet(0);

	public UserRole() {
	}

	public UserRole(int id) {
		this.id = id;
	}

	public UserRole(int id, String roleName, Set users) {
		this.id = id;
		this.roleName = roleName;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "UserRole [id=" + id + ", roleName=" + roleName + ", users=" + users + "]";
	}
	

}
